language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt codecov
script:
  - flake8 --ignore=E501
  #- python manage.py runserver
  - pytest sistemaWB/ --cov=sistemaWB
after_success:
  - codecov