language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt codecov
  - cp contrib/env-sample .env
script:
  - flake8 sistemaWB/ --ignore=E501
  - pytest sistemaWB/ --cov=sistemaWB
after_success:
  - codecov